### ISSUE TITLE
Simple DLLs Doesnt work

### ISSUE THREAD

**Issue by brk1337** [ddxoft/master#29]
Windows version: Windows 10 Home Version 10.0.19044 Build 19044
General and HID dll works but I need simple dlls to work.

**Comment by ddxoft** [comment]
can't write register

brk1337 ***@***.***> 于2022年1月17日周一 18:57写道：

**Comment by brk1337** [comment]
Still can't figure out. What should I do sir?

**Comment by brk1337** [comment]
@ddxoft I disabled all anti-virus programs, disabled Windows Defender. Still getting same error.

**Comment by brk1337** [comment]
Can you send QQ?

**Comment by brk1337** [comment]
When I try to register DD94687.64.dll to test. Entry-point cant be found. 
![Ekran Alıntısı](https://user-images.githubusercontent.com/49535853/149897572-5b006fa6-8121-4502-bead-e22d6688347f.PNG)
