### ISSUE TITLE
Contact

### ISSUE THREAD

**Issue by Mturns** [ddxoft/master#36]
QQ is not available.
I want to buy offline version

**Comment by ddxoft** [comment]
200$ forever.

https://paypal.me/cnwz
paypal : ***@***.***

TKC ***@***.***> 于2022年2月15日周二 12:34写道：

**Comment by ddxoft** [comment]
thanks.

http://www.ddxoft.com/download/2022.0216.zip

TKC ***@***.***> 于2022年2月16日周三 00:48写道：

**Comment by TKC69** [comment]
thanks,
I got the download fine.
But I have one question.
 
what is different Simple, HID, General?
 
just, difference in how it works?
Or, is there a performance gap? (ex/ avoid detection from security programs)

**Comment by ddxoft** [comment]
password:TKC

TKC ***@***.***> 于2022年2月16日周三 16:54写道：

**Comment by Mturns** [comment]
what is different Simple, HID, General? just, difference in how it works? Or, is there a performance gap? (ex/ avoid detection from security programs)

**Comment by ddxoft** [comment]
S -> in normal times
G -> server
H -> games

**Comment by Mturns** [comment]
thx
