### ISSUE TITLE
Problem while mov/btn

### ISSUE THREAD

**Issue by igorjunior** [ddxoft/master#48]
.

**Comment by ddxoft** [comment]
no need

Igor Junior ***@***.***> 于2022年6月7日周二 11:00写道：

**Comment by igorjunior** [comment]
How can I contact you about the paid version?

**Comment by ddxoft** [comment]
200$ forever.
paypal

Igor Junior ***@***.***> 于2022年6月7日周二 23:04写道：

**Comment by igorjunior** [comment]
I would like to contact you first with some questions, do you have email or discord?

**Comment by ddxoft** [comment]
Email: ***@***.***

Igor Junior ***@***.***> 于2022年6月8日周三 04:19写道：

**Comment by igorjunior** [comment]
censoring, I sent an email to your profile's gmail.
