### ISSUE TITLE
驱动启动错误

### ISSUE THREAD

**Issue by TaeDDin** [ddxoft/master#6]
![image](https://user-images.githubusercontent.com/62174069/106382068-5859f480-6400-11eb-840f-a722db2387ea.png)
When I check with the Device Manager, the driver is installed well, but when I run the example code with Python, I get an error in driver operation and testSelf in the same folder as dll. If you run with 64, you will get DD initialization error. What can I do to solve it?

作为设备管理员，驱动程序安装得很好，如果用Python 执行预制代码，驱动程序就会出现错误，与dll在同一文件夹中的TestSelf。如果运行64， 将会显示DD初始化错误 。 怎样才能解决呢？

**Comment by ddxoft** [comment]
QQ:2827362732

TaeDDin <notifications@github.com> 于2021年1月31日周日 下午8:04写道：

**Comment by leonam1234** [comment]
same problem... Could you let me know how to solve this problem..?
